services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rent_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - mysql

    rent_db:
        container_name: rent_db
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: rent_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - ./ticket_db:/var/lib/mysql
        networks:
            - app-network

    web:
        container_name: rent_web
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    node:
        container_name: nodes
        image: node:20
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        command: bash -c "npm install && npm run build"

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
